name: 🚀 Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: checkboxes
    id: preliminary
    attributes:
      label: Is there an existing issue for this?
      description: Please [search the existing issues](https://github.com/mittwald/ddev-mittwald/issues).
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
